
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JimohAdebayo-DevOps/gridops-skeleton-python
    targetRevision: HEAD
    path: charts/python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
